FROM ghcr.io/graalvm/graalvm-ce@sha256:24fb7be20ec879165dbeeb4a5b7d98287607fc8ef3ba07c715da4f0cd44ba4d1 as BUILDER

ARG JAR_FILE
COPY ./target/${JAR_FILE} app.jar

# Install native image
RUN gu install native-image
# Build the native image of our app
RUN native-image
RUN native-image \
      --verbose \
      --allow-incomplete-classpath \
      --no-fallback \
      --no-server \
      --enable-all-security-services \
      -cp ./app.jar \
      org.example.DummyServer

# Runtime Docker Image
FROM ghcr.io/graalvm/graalvm-ce@sha256:24fb7be20ec879165dbeeb4a5b7d98287607fc8ef3ba07c715da4f0cd44ba4d1

# Copy the built Native Image from the build time image into the runtime image
COPY --from=BUILDER /org.example.dummyserver .

CMD sleep 10s && /org.example.dummyserver 8844 TLS /app/selfsigned.jks b0000m


